- name: Setup Real Root
  gather_facts: False
  hosts: "{{hosts}}"
  user: root
  tasks:
    - name: Install git code - limbo2
      become_user: appsrv
      git: repo=git@github.com:og200/limbo2.git
           dest=/local/appsrv/limbo2
           accept_hostkey=yes
           force=yes
           version=master
           key_file=/local/appsrv/.ssh/id_rsa

    - name: Install git code - compositor2
      become_user: appsrv
      git: repo=git@github.com:og200/compositor2.git
           dest=/local/appsrv/compositor2
           accept_hostkey=yes
           force=yes
           version=master
           key_file=/local/appsrv/.ssh/id_rsa

    - name: Install git code - pv
      become_user: appsrv
      git: repo=git@github.com:og200/pv.git
           dest=/local/appsrv/pv
           accept_hostkey=yes
           force=yes
           version=experiments
           key_file=/local/appsrv/.ssh/id_rsa

    - name: copy nginx config
      copy: src=../templates/nginx-{{ env }}.conf dest=/local/nginx-root/etc/nginx.conf owner=root group=root mode=600
