    - name: make local dir
      file: path=/local owner=root group=root mode=755 state=directory

    - name: Install git code - unixtools/perllib
      become: yes
      become_user: root
      git: repo=https://github.com/unixtools/perllib.git
           dest=/local/perllib
           update=yes
           force=yes
           version=master
